### ISSUE TITLE
Autocomplete suggest not contain objects from database after IntelliSense update

### ISSUE THREAD

**Issue by s-shamesmuhametov-parc** [microsoft/vscode-mssql#1011]
- MSSQL Extension Version: 1.2.0
- VSCode Version: 1.17.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open new tab.
2. Select language SQL
3. Input "Select * From "
4. Connect to database
5. While update intelisense input part of scheme name and press Ctrl+Space
6. After it is updated press Ctrl+Space again - suggest not contain scheme name
7. After input any symbol - suggest work and contain schema name, but I want it to work in 6 step

It seems that this is a small problem that is actually very annoying.

**Comment by kevcunnane** [comment]
Thanks for raising this. My understanding is that this is a "by design" behavior in how Visual Studio Code implements caching for suggestions. In order to speed up results, the suggestions are cached until additional text is added / the location is changed. I don't believe we have a way to wipe out their cache - perhaps you could open an issue to support doing this in the vscode repository?

**Comment by s-shamesmuhametov-parc** [comment]
Ok. Thanks for answer. Probably it is really so. I created issue in VS code https://github.com/Microsoft/vscode/issues/37020
