### ISSUE TITLE
MSSQL 2008 Unable to connect.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Microsoft/vscode-mssql#1012]
- MSSQL Extension Version: 1.25.0
- VSCode Version:  1.17.0
- OS Version: Ubuntu 17
- SQL Server: 2008 R2

Steps to Reproduce:

1. Install extension to VS Code & reload.
2. Attempt to make connection.

Error: Unable to connect using the connection information provided.
Error-2: Connection Timeout Expired. ...

![image](https://user-images.githubusercontent.com/1968109/32085162-f7e937a0-bb29-11e7-9a44-4ec7174544c7.png)

Is there some kind of configuration i'm missing to support older sql server?
I know that there was for a node.js module and for perl to connect.
Im pretty sure the connection details are correct as I use them elsewhere on this computer. (For JDBC though).

It is using an instance name however such as:
```
10.1.1.5\Server1
```

**Comment by kevcunnane** [comment]
@LiamKarlMitchell I believe this is the same issue as https://github.com/Microsoft/vscode-mssql/issues/666#issuecomment-277384388. The solution is to update your server to SQL Server 2008 SP3 or greater. This is required as there was a security issue fixed in this version, and the .Net Core drivers we use intentionally do not support connecting to earlier versions.

**Comment by LiamKarlMitchell** [comment]
I see.. that could be a pain point.

Note: Update the read me to point out the db connector only supports SQL Server 2008 SP4+ or something of that effect.

I'll read up on the upgrades and let those in charge know, and hope for the best.
Some good info in the other post thanks.
