### ISSUE TITLE
mssql intellisense helps with tables, but kills the built in intellisense for sql.

### ISSUE THREAD

**Issue by klukiyan** [Microsoft/vscode-mssql#1023]
- MSSQL Extension Version: 1.21
- VSCode Version: 1.17.2
- OS Version: win7 and win 10 (both machines same behaviour)

Steps to Reproduce:

1. Set mssql intellisense to true ```"mssql.intelliSense.enableIntelliSense": true```
2. Declare ```@SomeVariable```  
3. Start typing it on next line. The intellisense won't "help you"!.
4. Now set mssql intellisense to false ```"mssql.intelliSense.enableIntelliSense": false```
5. Try again. It will work fine.

**Why does mssql's intellisense kill the existing intellisense. Can't they work together?!**

**Comment by MattIrv** [comment]
Thanks for the report. I think I can reproduce this issue, but it only happens when there are blank lines or other content on the same line or subsequent lines where you are typing.

For example with the following query, if I start typing `SET @test = 5` or something like that on line 2 then I don't get autocompletes for it (unless I press ctrl+space), but if I add a new line at the end and start typing, then I do get autocomplete (unless I have blank lines following it).

```
DECLARE @test int;

DECLARE @test2 int;
```

@klukiyan can you confirm whether this is this the same behavior you're seeing? Thanks!

**Comment by kevcunnane** [comment]
This should be fixed. We now always return a result. Before the intellisense process would wait for us to respond and hence not provide the built-in intellisense. This was shipped in December

**Comment by klukiyan** [comment]
Thank you :)
