### ISSUE TITLE
SQL Tools Service component exited unexpectedly. Please restart SQL Operations Studio.

### ISSUE THREAD

**Issue by DihoKing** [Microsoft/vscode-mssql#1034]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.2.9200
---
Version 0.23.6
Commit 8a3011756318a2ded1e6e84332230a2b2bf9c544
Date 2017-11-06T21:51:43.232Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS: Win 10 Fall Creators

Steps to Reproduce:
1.Start normally show a white space  window!
2.Start in Compatibility windows 8 mode causes  SQL Tools Service component exited  unexpectedly
![error](https://user-images.githubusercontent.com/11072891/32990415-4b7b04fe-cd3e-11e7-9967-e71529578987.PNG)

**Comment by MattIrv** [comment]
Hi @DihoKing, please be aware that this is the repo for our VS Code extension and not for SQL Ops Studio. You can find that repo at https://github.com/microsoft/sqlopsstudio

To address your issue, please run SQL Ops Studio without compatibility mode. If that doesn't work because of some bug, please file an issue for that bug in the SQL Ops Studio repo at https://github.com/microsoft/sqlopsstudio

Thanks!
