### ISSUE TITLE
Again SQL Syntax Highlighting not working when escaping strings

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-mssql#1047]
_From @MikeVelazcoMtz on December 9, 2017 0:49_

I'm creating again this issue because @isidorn closed #39822 and didn't even took a moment to test if the issue is really part of the core or an extension.

- VSCode Version: 1.18.1
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Create a SQL query escaping something inside a string (See GIF)
![error_vscode_3](https://user-images.githubusercontent.com/5341310/33680479-5d3d8a58-da87-11e7-9f67-ec8b74ed551b.gif)

Reproduces without extensions: Yes

IT CAN BE REPRODUCED WITHOUT ANY EXTENSION ENABLED

_Copied from original issue: Microsoft/vscode#39950_

**Comment by aeschli** [comment]
_From @isidorn on December 11, 2017 9:31_

@MikeVelazcoMtz sorry about that, my mistake

**Comment by aeschli** [comment]
We use the SQL grammar from https://github.com/Microsoft/vscode-mssql.
When fixed there, we will update our grammar file.

**Comment by MattIrv** [comment]
Hi @MikeVelazcoMtz,

It looks like you're using MySQL or another similar flavor of SQL, correct? In MySQL, string literals in double quotes and escaping using a `\` character are valid, but they are not part of the SQL standard and are not valid in many other SQL flavors. Because there are so many different flavors of SQL, it is not possible for flavor-agnostic syntax highlighting to handle them all correctly.

If you need MySQL highlighting, I would recommend searching the VS Code extension marketplace to see if there are extensions that provide it.

Hopefully this helps answer your question. If you have any other questions or feedback please let me know, otherwise I will close this issue. Thanks!
