### ISSUE TITLE
Does this add-on work on MySQL?

### ISSUE THREAD

**Issue by bergamin** [Microsoft/vscode-mssql#1049]
I've just installed VSCode in a new PC that has MySQL installed. VSCode suggested me to use this add-on because of that, but I don't see MySQL anywhere in the Wiki page.

Is it really supported?

Thank you very much! I use this add-on at work and would love to be able to use it at home as well.

**Comment by kuacci** [comment]
I guess it cannot connect to MySQL. It's only for ms sql.

**Comment by bergamin** [comment]
just as I suspected... thanks, @kuacci

**Comment by kburtram** [comment]
@bergamin this extension only supports SQL Server at this time.  I believe there are a couple other VS Code extensions that supported MySQL though.  Also, you can change the target SQL language flavor to prevent this extension from raising syntax errors for MySQL-specific SQL syntax.

I'll close this issue now since this isn't a scenario we plan to support in the near future.  Thanks!

**Comment by bergamin** [comment]
Thanks, @kburtram. I was expecting for that, but was surprised by VS Code suggesting the use of it for me having MySQL installed on my PC. I guess I should open a ticket there for fixing this misunderstanding...

**Comment by shane-lennon** [comment]
> @bergamin this extension only supports SQL Server at this time. I believe there are a couple other VS Code extensions that supported MySQL though. Also, you can change the target SQL language flavor to prevent this extension from raising syntax errors for MySQL-specific SQL syntax.
> 
> I'll close this issue now since this isn't a scenario we plan to support in the near future. Thanks!

How do you change the target language flavor ?
