### ISSUE TITLE
Change comma by semicolons to export csv

### ISSUE THREAD

**Issue by guruznet** [Microsoft/vscode-mssql#1078]
- MSSQL Extension Version: 1.3.0
- VSCode Version: 1.21.1
- OS Version: macOS High Sierra 10.13.4

How can I change comma by semicolon to export to csv?

Regards,

**Comment by kevcunnane** [comment]
This isn't currently supported. We welcome community contributions and this is a good candidate. The basic steps would be:
- Add a configuration setting to choose the delimiter used when exporting to CSV
- Send this as an additional field in ther request to the backend service, and update the [SaveResultsAsCsvRequestParams](https://github.com/Microsoft/sqltoolsservice/blob/376cc21f12a527c47391f21366e4935798f196bd/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/Contracts/SaveResultsRequest.cs#L74) in the backend to accept it
- Update the [SaveAsCsvFilestreamWriter](https://github.com/Microsoft/sqltoolsservice/blob/376cc21f12a527c47391f21366e4935798f196bd/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/DataStorage/SaveAsCsvFileStreamWriter.cs#L57) in the SqlToolsService backend to use the new parameter instead of `'`.

At the moment, we don't have plans to do this work so I'm adding Help Wanted and opening this for community contribution. Thanks for raising the issue!
