### ISSUE TITLE
[ERROR] Error: Request error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by Khandfw** [Microsoft/vscode-mssql#1089]
- MSSQL Extension Version: 1.3.1
- VSCode Version: 1.22.2
- OS Version: Win10 64bit

Steps to Reproduce:
![vs_code mssql](https://user-images.githubusercontent.com/25910265/39076290-19245984-44c0-11e8-897f-93a2162235a8.JPG)
![vs_code mssql_2](https://user-images.githubusercontent.com/25910265/39076291-194e3286-44c0-11e8-8005-043225a4674a.JPG)
![vs_code mssql_3](https://user-images.githubusercontent.com/25910265/39076292-1987b498-44c0-11e8-98c2-929bee1ca529.JPG)
![vs_code mssql_4](https://user-images.githubusercontent.com/25910265/39076294-19d8c4a0-44c0-11e8-9452-8aab5e324e5f.JPG)
![vs_code mssql_5](https://user-images.githubusercontent.com/25910265/39076295-1a076198-44c0-11e8-92b4-27885b9e32b2.JPG)
[VSIXInstaller_c4dcb5e2-1acc-4f26-8a68-f01c56f09ca7.log](https://github.com/Microsoft/vscode-mssql/files/1933849/VSIXInstaller_c4dcb5e2-1acc-4f26-8a68-f01c56f09ca7.log)

1. Download mssql-1.3.1.vsix.
2. Open Visual Studio Code.
3. Hit F1 Type VSIX and choose Extensions: Install from VSIX.
4. Reload Visual Studio Code when prompted.

**Comment by MattIrv** [comment]
Thanks for this report @Khandfw. It looks like something about your network is causing problems with our download website, likely something to do with your firewall if you're on a corporate network.

Since this can be a common problem we release packaged vsix files for each platform here on GitHub, so as a workaround you should be able to download and install the specific vsix for your platform (it looks like that's [`mssql-1.3.1-win7-x64.vsix`](https://github.com/Microsoft/vscode-mssql/releases/download/v1.4.0-alpha.7/mssql-1.3.1-win7-x64.vsix)) from our [1.3.1 release](https://github.com/Microsoft/vscode-mssql/releases/tag/v1.4.0-alpha.7). If that doesn't solve your issue please let me know.

**Comment by Khandfw** [comment]
Issue resolved, please close.

**Comment by jaykilleen** [comment]
I am also having a similar issue after our corporate network changed to a new https proxy software. I have tried to install v1.5 vsix manually however the extension still attempts to download the `sqltoolsservice` and encounters the error. Do I also need to install `sqltoolsservice` manually via `.vsix`??

```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to C:\Users\loivhpiouvhn\.vscode\extensions\ms-mssql.mssql-1.4.0\sqltoolsservice\1.4.0\Windows.
Downloading https://download.microsoft.com/download/3/2/9/32995640-2B4A-4C47-8764-287485C733DB/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.1.zip
[ERROR] Error: Request error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```

**Comment by jaykilleen** [comment]
OK got it working. Figured I should trial and error it instead of waiting. I extracted the zip file and copied all of the contents (except for the parent folder) into the vscode extensions path for `mssql` at `C:\Users\KilleenJ\.vscode\extensions\ms-mssql.mssql-1.5.0\sqltoolsservice\1.5.0-alpha.79\Windows`.

![image](https://user-images.githubusercontent.com/4168099/55604384-d45a6580-57b2-11e9-84d2-20abe25e5d52.png)
