### ISSUE TITLE
List of Errors Are Not Cleared When I close SQL File

### ISSUE THREAD

**Issue by lyndonjohn** [microsoft/vscode-mssql#1131]
Issue Type: **Bug**

I have an sql file generated from sequelpro.
Saved that file in my workspace.
Open file from my workspace.
Errors appear in status bar and integrated terminal.
I closed the file, but the errors are still there.

![screen shot 2018-07-30 at 8 30 39 am](https://user-images.githubusercontent.com/29518229/44063848-f7570dd0-9f94-11e8-97ab-255111a21c53.png)

Extension version: 1.4.0
VS Code version: Code - Insiders 1.26.0-insider (207ace21dfec3dccab52f1296a3880ac7644c978, 2018-08-10T06:40:10.035Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.37GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_10738237|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by MattIrv** [comment]
@lyndonjohn It looks to me like VS Code's behavior here is to show problems for all files in your open workspace/folder even if you don't actually have a tab open for the file. If you're seeing something that's specific to the sql extension here please reopen the issue and let me know, otherwise you can provide feedback on VS Code in their repo at https://github.com/microsoft/vscode if you want. Thanks!

**Comment by lyndonjohn** [comment]
@MattIrv Im pretty sure this is not vs code's problem. I tried disabling mssql extension and the errors are gone when i opened and closed .sql file, same with other files that has errors. I'm only experiencing this with .sql files. This is also happening in stable version of vs code. I'll just disable the extension for now. Thanks.

PS. I've already report this issue to vscode and they told this is mssql entension issue.

**Comment by MattIrv** [comment]
@lyndonjohn do you happen to have the link to the vscode issue you filed? The errors go away when you disable the extension because the errors themselves are coming from the mssql extension, but I think it's a VS Code issue because in general when an extension looks for errors it reports them for all the files you have in your workspace or active folder, not just the files you have open, but it may only find them when you open them. For example I have a typescript file that I added an error to and closed, and I see the same behavior:

<img width="466" alt="Errors reported for Typescript file after closing it" src="https://user-images.githubusercontent.com/3758704/44612684-22d86800-a7bf-11e8-9669-21ef82ee000a.png">

**Comment by lyndonjohn** [comment]
Here's the link: https://github.com/Microsoft/vscode/issues/55345
In other files that has errors, the error goes away when I close the file, but not with .sql file.

**Comment by lyndonjohn** [comment]
Thanks for your time @MattIrv.

**Comment by radoslavpetranov** [comment]
I am using the `mssql` extension for color highlighting, formatting, etc. I don't really need it to check the validity of my queries so showing a thousand errors was a little annoying and was getting in the way of seeing actual TS/code errors. If anyone is having the same problem as me and just want to hide the errors:

![image](https://user-images.githubusercontent.com/2715732/67144316-7a644d80-f275-11e9-93d8-d55a3e23bdfc.png)

1. Go to the plugin's settings
![image](https://user-images.githubusercontent.com/2715732/67144332-97991c00-f275-11e9-9f55-89daee666db0.png)

2. Find the `Enable error checking` option and disable it
![image](https://user-images.githubusercontent.com/2715732/67144302-64ef2380-f275-11e9-801f-5e1d60c2ef40.png)

3, All SQL errors are gone.
![image](https://user-images.githubusercontent.com/2715732/67144324-894b0000-f275-11e9-8a9e-7724c610464e.png)

Hope this helps someone.
