### ISSUE TITLE
Parameter placeholders show up as linting errors

### ISSUE THREAD

**Issue by dannyfraser** [microsoft/vscode-mssql#1138]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.26.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create a query using '?' as a parameter placeholder
2. Look at the Problems panel

![image](https://user-images.githubusercontent.com/1719752/44842415-a5d54480-ac3d-11e8-923c-58956645dfdb.png)

This isn't really a problem - I *want* there to be a question mark there! Is there a way of ignoring these particular linting errors?

**Comment by kevcunnane** [comment]
Not at present. I _think_ that if you used a SQLCMD variable like `'$(myVar)'` it wouldn't complain since that's an understood concept. Unfortunately we don't currently have an option to do SQLCMD variable replacement in our cross-plat tools yet so you'd still have to manually replace before running.

**Comment by abist** [comment]
SQLCMD is now available.
