### ISSUE TITLE
SQL 2005 from VSCode on Ubuntu 18.10

### ISSUE THREAD

**Issue by byroniac** [Microsoft/vscode-mssql#1165]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.29.0
- OS Version: Ubuntu 18.10

Have tried every way I know of to connect to a default instance of SQL 2005. I realize that version is not supported any more. But we will begin the process of upgrading to a SQL 2016 server soon, and it would be very nice to connect to this older SQL server. For whatever it is worth, the "sqsh" utility is able to connect, but it is not using the same connection driver.

Steps to Reproduce:

1. "connectionString": "Server=tcp:SERVER\\MSSQLSERVER,1433;Database=DB;User Id=xxx;Password=xxx" JSON, tried with and without the "\\MSSQLSERVER".
2. Get "Connecting" prompt and takes forever, nothing ever happens.

**Comment by MattIrv** [comment]
We rely on .Net Core's SqlClient library here. They have an open issue for this but it's unlikely that it will be addressed since SQL 2005 is not supported. See https://github.com/dotnet/corefx/issues/15424 for more. Unfortunately the best I can recommend is to use Windows or use other utilities as a workaround like you have been

**Comment by byroniac** [comment]
Thank you for that link. Hindsight being 20/20, we should have upgraded long ago.

**Comment by kevcunnane** [comment]
I believe that you need SQL Server 2005 upgraded to SP4 in order to run. There was a breaking security change that affects 2005 and 2008 servers where in .Net Core, it intentionally will not connect to a server without that change applied. Therefore, updating to that usually solved it for previous folks who had this problem.
