### ISSUE TITLE
Printing spaces in VS Code -- multiple spaces get removed from within a string

### ISSUE THREAD

**Issue by RBJORNSSON** [Microsoft/vscode-mssql#1178]
PRINT 'Tag: (imagine lots of spaces here .... github removes them too ... fail) Total'  
becomes:  
Tag: Total  
in VSCODE, whereas it is:  
Tag: (spaces remain in SSMS) Total  

Why is it removing all the spaces in VS Code? -- I didn't ask it to.

**Comment by RBJORNSSON** [comment]
And why is it removing them in github as well?

**Comment by benrr101** [comment]
My guess is that this is caused by HTML treating multiple whitespace as one space. VSCode and https://github.com/Microsoft/azuredatastudio use Electron which is essentially a Chromium renderer. This means that it is basically rendering webpages that would adhere to the rules of HTML. The traditional workaround for webpages is to use the non-breaking space `&nbsp;` for in place of repeated spaces.
