### ISSUE TITLE
Code Folding with #region

### ISSUE THREAD

**Issue by dticson** [microsoft/vscode-mssql#1183]
Is there a way to enable VS code code folding with #region markers? I do not see it listed in any documentation or in the options.  If not, please add this to list of requested features.

Thanks!

**Comment by unixwitch** [comment]
I'd find this helpful too.  I'm working on some fairly large (thousands of lines) SQL files where queries are formatted like this:

```sql
INSERT INTO table (...)
SELECT ...
FROM ...
LEFT JOIN ...
WHERE ...
etc
```

Since each part of the query starts from the leftmost column, VS Code's default indent-based folding doesn't work very well.  I'd also find it useful to fold larger regions containing multiple related queries.

I think `--#region` and `--#endregion` should work fine as folding markers.  SMSS doesn't seem to have any folding marker comments of its own that could be re-used, although it will treat `BEGIN ... END` as a foldable region.

**Comment by xinthose** [comment]
It does not seem to want to work for me:

``` sql
-- #region

select now();

-- #endregion
```
