### ISSUE TITLE
SELECT TOP (1000)  Why can not set to other number ?such as 10 row ???

### ISSUE THREAD

**Issue by makelove** [microsoft/vscode-mssql#16994]
why I click "SELECT TOP (1000) " ,it auto open the result tab

I don't want this !!!

any custom setting cann't find !!!

**Comment by makelove** [comment]
another problem is Cannot open new query tab 
always have to select "Script as Create" to open new query tab 
then modify the SQL

unbelievable !!!


macOS 10.15.3
版本: 1.56.2
提交: 054a9295330880ed74ceaedda236253b4f39a335
日期: 2021-05-12T17:44:30.902Z (2 周前)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.3.0

**Comment by kburtram** [comment]
@makelove thanks for opening this issue.  There are few different questions in the comments, that I can try to help answer?

1. The number of rows return is hardcoded to 1000.  we could make this a setting, though we have received other feedback that we have too many settings and it makes the tool harder to configure & use.  Is the primary reason you'd like to configure this perf related to retrieving the rows, or something else?

2. We don't currently have a setting to generate the SELECT statement without executing it.  This is a reasonable suggestion.  You may consider using the sqlSelect snippet as a workaround for quickly generating a SELECT statement without execution.  I realize it's not quite the same.

3. We have New Query context menus on the Connection and the Database nodes in the Object Explorer tree (screen capture below for reference).  But we didn't put in on the table.  The thinking was most people interacting with the table would prefer either generating a SELECT or CREATE statement for that table instead of an empty query window.  You can also get a new query windows by opening a new file document and changing the language mode to SQL.

![image](https://user-images.githubusercontent.com/599935/120085634-bdf87d80-c08e-11eb-9308-710e39b1ea3b.png)

Hope that helps to at least provide some context on the features.  I'll leave this issue active for the new settings suggestions.
