### ISSUE TITLE
Repeated keychain prompts in v1.10.2 & 1.11.0

### ISSUE THREAD

**Issue by leighghunt** [microsoft/vscode-mssql#17064]
- MSSQL Extension Version: v1.10.2
- VSCode Version: 1.60.2
- OS Version: BigSur 11.5.2

Steps to Reproduce:

1. Start VS Code
2. Open SQL file
3. Shift-Cmd-E to execute
4. Choose connection profile
5. Dialog appears - **MicrosoftSqlToolsServiceLayer wants to use your confidential information stored in "M" in your keychain**
6. Enter password and click **Allow** or **Always Allow**.
7. Query will run, and can then be run successfully for rest of session.
8. However, if you disconnect and then reconnect to database, our restart VSCode, the security dialogue reappears.
<img width="447" alt="Screen Shot 2021-10-01 at 10 44 59 AM" src="https://user-images.githubusercontent.com/349153/135534423-052a440e-3991-40bc-be13-4365ed337538.png">

Note - if this is simply because it's a preview release and is perhaps unsigned, or something like that kicking off MacOSX being fussy, happy to close ticket.

Thanks for the work on getting it working on M1.

**Comment by kburtram** [comment]
@leighghunt thanks for reporting!  It shouldn't be related to this being a preview build so we'll investigate to ensure this doesn't also impact the upcoming 1.11.0 build.

**Comment by kburtram** [comment]
@cssuh can you take a look if anything's changed here in 1.11.0?  I think when we push an update users will need to reenter their keychain password to access saved passwords using the new binary, but this should be a one-time (or at least one-time per password).  Not something that keep reoccurring.

**Comment by kburtram** [comment]
A few follow-up questions/responses regarding previous comments...

@chigia001 this extension saves credentials in the keystore for saved connections.  You should only get this prompt when connecting to a server, so if it's happening outside that scenario then that sounds like an unintended design change.  When the extension is updated the binary that reads these keys is updated and needs to be granted permissions to the keychain again.

@sharumpe @boxofyellow it's strange that this is happening on startup if you aren't connecting to a server.  Chris will investigate what's going on there.  Are you granting SQL Tools Service access and then it continues to prompt subsequently, or are you denying STS permissions?

@benzdouglas you would need to grant STS permissions to the keychain to read saved credential information and establish a connection.  Though this should be a one-time thing after upgrade.  Downgrading may workaround this issue since the previous version of STS may already have permissions to the keychain.

Please let me know if we're missing any details with this issue.  Thanks!

**Comment by sharumpe** [comment]
> A few follow-up questions/responses regarding previous comments...
> 
> @sharumpe @boxofyellow it's strange that this is happening on startup if you aren't connecting to a server. Chris will investigate what's going on there. Are you granting SQL Tools Service access and then it continues to prompt subsequently, or are you denying STS permissions?

I have been clicking "Deny", but I just restarted to have a go at it again.  I was prompted a total of two times for the same thing (wants access to "a" in the "login" keychain).  I entered my creds and clicked "Allow".

Both ways (allow and deny) seem to end up with me being able to use the connections I've got set up on the SQL Server tool pane.

**Comment by kburtram** [comment]
@sharumpe thanks for the additional context.  It's interesting the connect still works when you click Deny.  We'll continue to investigate.

**Comment by leighghunt** [comment]
Some additional info, which may (or may not) help, I think I uninstalled the preview release back when I experienced the issue - and now appear to be using the normal v1.10.2 version (not via preview) and I'm not experiencing the issue.
![Screen Shot 2021-11-04 at 8 38 18 AM](https://user-images.githubusercontent.com/349153/140180829-c7cf9108-1fb8-47a1-a2d5-0994eb95f8ba.png)

I then updated to version v1.11.0 as suggested by extension, and again no problems with the keychain prompts.

![Screen Shot 2021-11-04 at 8 41 37 AM](https://user-images.githubusercontent.com/349153/140181601-758f8ecc-7b35-4fbe-bbe4-f20327460f43.png)

Out of curiosity, I uninstalled the extension, and attempted to redownload the preview version again from https://github.com/microsoft/vscode-mssql/releases/tag/v1.10.2, to verify the issue still occurred, but it seems to be automatically updating to v1.11.0 - I can no longer reproduce the issue.

Please let me know if you'd like me to try any tests.

**Comment by kburtram** [comment]
I've been able to reproduce this now in my environment.  I've typically selected "Always Allow" which makes the prompt go away, which is why I wasn't seeing this.

There is some change in 1.11.0 where we seem to be unnecessarily trying to read credentials on startup.  We should access the keychain when trying to connect and it's necessary to retrieve the saved encrypted credentials.  We're investigating what's changed and will likely push a 1.11.1 update with the fix.

Obviously selecting "Always Allow" should suppress this prompt.  Though I certainly understand if users prefer to be prompted each time their keychain is accessed.  For what it's worth, you can review the code we use to access the keychain here and in related files if there is any concern regarding that https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.Credentials/Credentials/OSX/OSXCredentialStore.cs.

**Comment by sharumpe** [comment]
I had the opportunity to do a little more thorough testing this morning, and I need to correct my earlier statement:
If I click "deny" I am _not_ able to connect to configured databases.  Providing my password and clicking "Allow" does allow those connections, of course.

**Comment by kburtram** [comment]
@sharumpe thanks for the clarification.  It was a bit of a mystery (*concern*) how the connection would work after denying the prompt.  We're investigating why we're trying to read saved credentials when we don't need to (basically any time other than when establishing a connection).

**Comment by CodingSamurai** [comment]
Just started getting the same issue today as well after rebooting.

**Comment by kburtram** [comment]
The 1.11.1 release we published today should no longer have a keystore prompt on vscode startup.  Please let us know if this is not the case in your environment.  Thanks!

**Comment by ibrowne** [comment]
I'm experiencing this on v1.13.0.  I've always clicked "Always allow" and the prompt goes away usually after the SECOND time of going through the process of entering my PW and clicking "Always Allow". 

**Here's what's different though:** 
  * I have to do this each time I connect to a different database (go through the prompt twice)
  * The prompts don't come back UNTIL there's an update installed, then I have to go through the whole thing again for each database.

Is there a way to set something so that "always allow" actually means ALWAYS?  Even after an update is installed?

**Comment by joelricci** [comment]
Is there a way to **deny** access and not having the prompt pop up every time I start VSCode? 

I just want to use the extension for local development and it's an annoyance having it popping up from time to time.

Identifier: ms-mssql.mssql
Version: 1.30.0
