### ISSUE TITLE
Language set to SQL, errors highlighted as PowerShell

### ISSUE THREAD

**Issue by Liturgist** [microsoft/vscode-mssql#17386]
- MSSQL Extension Version: 1.15.0
- VSCode Version: 1.68.1
- OS Version: Microsoft Windows 10 Enterprise 10.0.19042

Steps to Reproduce:

1.Select language Ctrl-K,M as SQL

The yellow underscored "SELECT" message appear to be indicating that it is being interpreted as PowerShell instead of SQL. Is this the correct place to post this.

![image](https://user-images.githubusercontent.com/2530958/177413524-493a0baa-1c48-43c5-80ae-07cdc8ecc9c2.png)

**Comment by Charles-Gagnon** [comment]
I've tried to repro it but I can't seem to get that to happen. Could you give the full set of steps from opening the new file to when you saw this issue? Might be a problem with how the text is entered or something.

But this isn't something I think we're going to be able to help with - if VS Code is getting confused about the language that is likely a core issue on their end since we don't control what language a doc has at all. So it would probably be best to open an issue in the VS Code repo instead.
