### ISSUE TITLE
Unable to connect via 2FA - "This site can't be reached"

### ISSUE THREAD

**Issue by dvasdekis** [microsoft/vscode-mssql#17395]
- MSSQL Extension Version: v1.15.0
- VSCode Version: 1.68.1
- OS Version: Windows 10 Enterprise 21H2

Steps to Reproduce:

1. ctrl+shift+p, create new connection, enter SQL Server details
2. Link is generated, like `http://localhost:61997/signin?nonce=PnOsArasdasdasfk2fHhch%252BA%253D%253D`
3. Go to link, but it says "This site can’t be reached. localhost refused to connect." Not sure how to debug further.

Unlike https://github.com/microsoft/vscode-mssql/issues/17234, I don't get the chance to click an account name.

I don't have a choice but to use 2FA for Synapse SQL OnDemand servers, so I don't have an alternative at this time to this approach.

**Comment by Charles-Gagnon** [comment]
Are you able to use the device code auth method?

![image](https://user-images.githubusercontent.com/28519865/178639364-7145ef3a-24ca-40c7-b2e7-bb414c8aae7b.png)

**Comment by Katzmann1983** [comment]
First step is always to completely delete your browser history. Some cached tokens there (especially when changing passwords) might screw over this extension.

**Comment by jan-hudec** [comment]
> Are you able to use the device code auth method?
> 
> ![image](https://user-images.githubusercontent.com/28519865/178639364-7145ef3a-24ca-40c7-b2e7-bb414c8aae7b.png)

For me the DeviceCode works.



> First step is always to completely delete your browser history. Some cached tokens there (especially when changing passwords) might screw over this extension.

Cached tokens, nor anything else in the browser local storage, did not get opportunity to screw anything yet, because the link the browser was given cannot be opened. Because the server in the extension appears not to be listening.

Besides, telling the user to just clear local data when problem occurs, especially all local data rather than local data for specific site, is rude. Some of the data in local storage are rather important and will cost significant time to recreate or restore later.

**Comment by cheenamalhotra** [comment]
Checking in, does anyone still experience this issue? We are hopeful this issue should be resolved, let us know if you're experiencing any Azure authentication issues.

**Comment by cheenamalhotra** [comment]
Closing as inactive issue
