### ISSUE TITLE
Grammar doesn't supports backslash escape character for single quoted strings

### ISSUE THREAD

**Issue by rishky-msft** [microsoft/vscode-mssql#17455]
- MSSQL Extension Version: 1.16.0
- VSCode Version: 1.71
- OS Version: Windows 10 64 bit

Steps to Reproduce:

1. Open new text.sql file in vscode.
2. Enter text 'vscode\\'s bug'.   Instead of highlighting complete text, only 'vscode\\' will be highlighted.

**Comment by Charles-Gagnon** [comment]
@rishky-msft T-SQL doesn't escape quotes with backslashes, it doubles up the quotes for that (e.g. `vscode''s bug'`)

I assume you're using this for your MySQL extension - in which case it would probably be best for us to each have our own grammar files that are contributed to VS Code so that users can choose which one they use based on what server engine they're using.
