### ISSUE TITLE
SQL Query Grid Results

### ISSUE THREAD

**Issue by aalkhatib9** [microsoft/vscode-mssql#17503]
The Query Grid Results Always open up in a new tab. Makes it difficult for Analysis.
Azure Data Studio on the other hand pins the Query Results to the bottom of each SQL Query.

I added two screenshots to demo the difference between how the results are displayed. 
I tried in many different ways but I'm not able to Pin the results per Query Code in Visual Studio Code? 
If there is a way to do so, can you please pass me the instructions? 
If there isn't, can you please tell me how I can request it as a future enhancement? 

VsCode is preferred for SQL Coding/text editing because of its powerful capabilities and powerful extensions such as Github CoPilot. Azure Data Studio on the other hand does have better data mining and exploration features, making it easier to read the results. 

One other side request if you don't mind.
If you notice: Azure Data Studio has filters on each field in the grid results. Can that also be possibly added? 
It's not a big deal and I can always filter using the where statement, but this would be a nice time saver if possible. 

Thanks for your support. 

![Visual_Studio_Code_SQL_Results](https://user-images.githubusercontent.com/61369640/208831530-4bed0fe0-fc36-4062-af5f-1092ddb99910.jpg)
![Azure_Data_Studio_SQL_Results](https://user-images.githubusercontent.com/61369640/208831553-5d5d5c76-d6d1-4cf6-9204-6660c2f54af6.jpg)

**Comment by kburtram** [comment]
Unfortunately, there is no way to pin the query results to the query text in VS Code, since there is no extensibility point to customize the editor documents.  Though we are working on a significant query results management UX redesign that will address several of the shortcomings in the vscode experience, and hopefully make it easier to do the type of analysis you outlined in vscode.  This will include client-side sorting & filtering of the result set, which we're tracking with issue https://github.com/microsoft/vscode-mssql/issues/17978.  Please let us know if there's anything else we can assist with.  Thanks for opening this suggestion.
