### ISSUE TITLE
Ctl+F when used in SQL Server Object Explorer - the Filter option does not filter to found results

### ISSUE THREAD

**Issue by whytheq** [microsoft/vscode-mssql#17539]
- MSSQL Extension Version: 1.17.1
- VSCode Version: 1.75.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Go to the SQL Server Object Explorer
2. Expand "Databases" folder
3. Expand specific database folder
4. Expand views folder
5. Press Ctrl+F
6. Type a search string
7. In the small Ctrl+F form select the 'Filter' button

At step 7, previously, the items in the tree would filter so only those found would be visible - now they do not filter and are simply highlighted. The above functionality still works for other extensions.

We have thousands of items in these object explorer folders, so this functionality is very useful.

**Comment by ibkhilji** [comment]
Yes i am also facing this issue

**Comment by kupdegrove** [comment]
This is apparently still a problem. I'm experiencing the same issue. It was working so I'm not sure what happened.

**Comment by Data-mite** [comment]
Also an issue here. Filtering seems unable to hide items which have items below them in hierarchy, so is not useful for tables, views, stored procedures, as each of these has components beneath them.

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra I'm putting this in September for consideration, I can verify that something does seem to have changed here so the filtering isn't working like it used to. That control is provided by VS Code so not a ton we can do directly about it - but it's possible there's something we're doing wrong or not doing with the tree provider that's making this happen. 

(and it'd be good to know what the problem is here for ADS as well, since presumably we could have someone run into the same kind of issue there)

**Comment by whytheq** [comment]
Excellent news it is being looked into. It seemed to happen around the time that Schemas became nodes in the object explorer - maybe just coincidental - just a thought.

**Comment by cheenamalhotra** [comment]
Same reason as explained here: https://github.com/microsoft/azuredatastudio/issues/24086#issuecomment-1669011404
This is external to extension.
