### ISSUE TITLE
SQL Language Basics - update Postgresql reserved words dictionary.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-mssql#17623]
It would be good to update the Postgresql dictionary - there are quite a lot of keywords that are not highlighted properly.
For example — perform, columns, int8, elsif, ...

From @shtoormanSam in https://github.com/microsoft/vscode/issues/177218

**Comment by Charles-Gagnon** [comment]
Thanks @alexr00 - currently this repo is really only for MSSQL (T-SQL) syntax so other SQL languages such as Postgres aren't really something we're planning on maintaining. And it would be pretty confusing to have syntax that's valid in Postgres also show up as valid in MSSQL - there's a lot of stuff that isn't shared between them.

It seems to me like we should be having multiple languages created for each "flavor" of SQL. Do you have any other suggestion for how to handle this situation? I looked at the language injection stuff too but that doesn't seem correct either - again because there isn't a single grammar that's valid for all flavors of SQL.

**Comment by alexr00** [comment]
@Charles-Gagnon thanks for the explanation! I'll re-open https://github.com/microsoft/vscode/issues/177218 since it doesn't make sense to have Postgresql here.

**Comment by dzsquared** [comment]
There's the postgres extension that would be the ideal place for this dictionary, but they haven't updated for a while: https://github.com/Microsoft/vscode-postgresql
