### ISSUE TITLE
mssql: Client is not compatible with the service layer

### ISSUE THREAD

**Issue by kisantia** [microsoft/vscode-mssql#17668]
I tried installing the latest vscode-mssql extension from the product build pipeline and saw this error when the extension is activated:

![image](https://user-images.githubusercontent.com/31145923/235510056-2105da4d-17e4-4f5c-8167-082399bea76c.png)

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra Could you look into this? Likely related to the latest STS update you did.

**Comment by cheenamalhotra** [comment]
It's happening since now the DLL version is not 1.0.0.x anymore, with your recent changes to modify Assembly versioning in STS.
https://github.com/microsoft/vscode-mssql/blob/e1af7814c96f6b9c662ad21e97cb1c36d62b1aca/src/constants/constants.ts#L104

is compared here:

https://github.com/microsoft/vscode-mssql/blob/e1af7814c96f6b9c662ad21e97cb1c36d62b1aca/src/languageservice/serviceclient.ts#L488-L494

**Comment by cheenamalhotra** [comment]
Do we really need this version check?

**Comment by Charles-Gagnon** [comment]
hah, yeah ok just remove that check. No good reason to have it.
