### ISSUE TITLE
Table Designer with Alter Scripting

### ISSUE THREAD

**Issue by TonyLugg** [microsoft/vscode-mssql#17871]
VS Code MSSQL extension is slick, fast, and intellisense is very useful.  After all these years why is SSMS still such a slug?  A nice feature would be a table designer, with the ability to generate an alter script.

**Comment by Benjin** [comment]
Good news: we've recently added a Table Designer with the ability to publish changes directly to a table or generate a script that handles all the changes for you!  It's in public preview as of 1.25.

Because it's in preview, you'll need to enable this flag:
![Image](https://github.com/user-attachments/assets/f470eb33-ccee-4882-bde5-99a54ab81e43)


Read more about the new Table Designer [here](https://github.com/microsoft/vscode-mssql/issues/17298)

![Image](https://github.com/user-attachments/assets/8059b561-921d-4b46-9d28-5ef36ab56952)

**Comment by TonyLugg** [comment]
Awesome!  For scripting, it is the Alter script that is what is needed.  It is easy to script a new table, but scripting changes to existing tables and handling the data migration to the new structure is what SSMS does that is needed here, including handling constraints and relationships, etc..

**Comment by Benjin** [comment]
I just pulled the screenshot from our docs page; I didn't mean to highlight that as the alter script alternative. 🙂

Because of those complexities you mentioned, alter scripts quickly get too complex to display a succinct version in the pane below, but if you click the "Publish" button at the top, then you'll have an option to "Generate script".  That's the full-fidelity DacFx-generated script for the ALTER action that includes all the constraint rebinding and data migration, exactly the same backend library as SSMS!

**Comment by TonyLugg** [comment]
Will this also be in Azure Data Services?

**Comment by Benjin** [comment]
Do you mean Azure Data Studio?  Table Designer has been in GA over in ADS since November 2022! 

![Image](https://github.com/user-attachments/assets/d99cbd13-de1c-4e27-8c6b-92011cdd6f9d)

**Comment by TonyLugg** [comment]
Yes. When the looked at it previously it didn't generate the same script as SSMS so it made me nervous.  I will have another look.

**Comment by Benjin** [comment]
Both the VS Code and Azure Data Studio table designers will generate scripts in two places for you: a simplified CREATE TABLE script (always CREATE, even if you're editing an existing table) in the bottom pane of the table designer, and a full-fidelity CREATE or ALTER TABLE script using DacFx.

SSMS's Import/Deploy functionality, SqlPackage, SSDT, and the SQL Azure Db Import/Export Service all use the same DacFx backend for making schema changes, so you know it's good!

![Image](https://github.com/user-attachments/assets/1a8d46bb-ebfd-46c5-b613-5048e43128c7)

![Image](https://github.com/user-attachments/assets/74803d6e-c8cf-4e81-8120-8c7108e81a7f)
