### ISSUE TITLE
support jTDS JDBC

### ISSUE THREAD

**Issue by winston9527** [microsoft/vscode-mssql#17946]
- MSSQL Extension Version: v1.22.1
- VSCode Version: Version: 1.91.1 (Universal)
- OS Version: MacOs 14.4.1 (23E224)

Steps to Reproduce:

This should be a requirement, not a bug.  Currently, vscode-mssql doesn't support changing the driver when creating a connection.  I'd like to use [jTDS](https://jtds.sourceforge.net/) to connect SQL server. I didn't find this feature

**Comment by kburtram** [comment]
Unfortunately this extension is tightly coupled with the Microsoft SQL Client Driver and it would be major refactoring in order to support different client drivers.  Due to this supporting additional drivers is out of scope for our current roadmap.  Thanks for opening this issue!  Please open an issue if there are specific features in jTDS that you'd like to see supported in this extension.
