### ISSUE TITLE
Type Error adding Azure DB with MFA

### ISSUE THREAD

**Issue by MichaelCWhitman** [microsoft/vscode-mssql#17944]
- MSSQL Extension Version: 1.22.1
- VSCode Version: 1.91.1
- OS Version: Windows 10 22H2 (19045.4529)

Steps to Reproduce:

1. Click "Add Connection" at the top of the Connections list.
2. Enter string as ******.database.windows.net
3. Enter default database
4. Select "Microsoft Entra Id - Universal w/ MFA Support"
5. Choose "Add a Microsoft Entra account..."
6. Sign in using the browser window that pops up
7. Enter a profile name, and press enter.

The command palette disappears, but nothing else happens in VSCode. The Window output shows "[error] [Extension Host] Could not add account: Type error: Cannot read properties of undefined (reading 'id')". Nothing shows under Output > MSSQL.

The same information works in Azure Data Studio.

This is a fresh install of VSCode as well.

**Comment by Benjin** [comment]
@MichaelCWhitman we recently (1.25/October) released a preview of a new connection dialog.  Have you had a chance to try connecting using that to see if the issue is still present?

You'll need to [enable the new features](https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#enabling-the-new-features) first.

https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#connection-dialog

**Comment by MichaelCWhitman** [comment]
> [@MichaelCWhitman](https://github.com/MichaelCWhitman) we recently (1.25/October) released a preview of a new connection dialog. Have you had a chance to try connecting using that to see if the issue is still present?
> 
> You'll need to [enable the new features](https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#enabling-the-new-features) first.
> 
> https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#connection-dialog

The issue is resolved with the new connection dialog. 

Thank you again!
