### ISSUE TITLE
Connection dialog doesn't open when using 'Add connection' button

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/vscode-mssql#18074]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open sql server OE 

3. Click on `Add connection` button at the top of the bar.
<img width="259" alt="image" src="https://github.com/user-attachments/assets/cd874b23-868a-4ab1-b5db-6f2b3f0d49e2">

3. The connection dialog opens with error and none of the fields are visible.
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/30111337-2d5e-442f-a69f-cf067d64a7bf">

This seems to happen on a newly installed extension with no existing connections

**Comment by aasimkhan30** [comment]
<img width="564" alt="image" src="https://github.com/user-attachments/assets/bb75e1d3-8480-4e21-9fee-0f2b54d13f03">
Here is a screenshot of console

**Comment by Benjin** [comment]
I tried taking a new .zip installation of VS Code (latest, 1.93.1) on Windows and the vsix built from [this PR run](https://github.com/microsoft/vscode-mssql/actions/runs/11023889049?pr=18073) and was not able to repro the issue.

My user JSON has no existing connections:
![image](https://github.com/user-attachments/assets/c043edfa-0714-43c6-937a-521ac2c089be).

I'll try on mac and with the `mssql.connections` config entry completely missing (rather than empty) to see if that causes the bug to appear.
