### ISSUE TITLE
Azure browse experience partially working

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18122]
Azure browse is partially working. It connects to Azure, it lists the existing subscriptions but the RG, Location and server drop-downs are empty.

![image](https://github.com/user-attachments/assets/3a0475ae-0ee0-4ba0-80c6-fc8dcf956a0e)

I see an opportunity to add a filter to the list of subscriptions. In my case, the list is large, and it took me a few minutes to find the subscription I wanted to use.

![image](https://github.com/user-attachments/assets/968a7e29-c525-4ec2-8e6f-0bd46f9de7c0)

Adding @jdesai-24 in case she has more comments from the design side.

**Comment by Benjin** [comment]
I hear you!  I also have 260 subscriptions, which is a bit unwieldy to work with.  Fortunately, you can already do subscription filtering if you either edit your preferences JSON:

```json
azureResourceGroups.selectedSubscriptions": [
    "<tenant ID>/<subscription ID>"
],
```

or use the Azure Resources extension to edit VSCode's built-in subscription filter:

![image](https://github.com/user-attachments/assets/54dc1ca1-2bca-49f2-8583-c07aa2418b9a)

I have an issue already assigned to me to add support for in-extension filtering (#18107) that'll edit the same config flag.  That config flag isn't my favorite naming scheme, but it's what the VSCode-provided Azure management libraries use.

**Comment by Benjin** [comment]
Were the dropdowns empty when you tried to open them?  The current behavior should have values loaded but they should default to being unset so that it doesn't preemptively filter your list of servers.

Also, we chatted a bit about ways to improve the filtering dropdowns at the end of the bug bash.  Some ideas that were brought up:

* automatically select the first item in the list when it's populated
* have some placeholder text in the dropdowns that prompts the user to select a resource group or location if they want to filter further

I'd love to get more thoughts on the best way to do this from you and @jdesai-24!
