### ISSUE TITLE
Reorder Advanced Connections Settings panel list

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18153]
Consider reordering the **Advanced connection settings** panel labels, according the following list:

1. General settings
  - Port
  - Application name
  - Connection timeout
  - Multi-Subnet Failover

2. Security and encryption (**Collapsed by default**)
  - Always encrypted
  - Attestation Protocol
  - Enclave Attestation URL
  - Persist Security Info
  - Host name in Certificate
  - Type system version

3. Database Initialization (**Collapsed by default**)
- Application Intent
- Command Timeout
- Current language
- Multiple Active Result Sets

4. Connection Resiliency & Failover (**Collapsed by default**)
- Connect Retry Count
- Connect Retry Interval
- Replication
- Failover Partner

5. Pooling Settings (**Collapsed by default**)
- Pooling
- Min Pool Size
- Load Balance Timeout
- Packet size

6. Data Source & Context (**Collapsed by default**)
- Attached DB file name
- Context Connection
- Workstation Id

Tagging @jdesai-24 for visibility

**Comment by Benjin** [comment]
I've reorganized the top options, renamed the groups, and localized the group names for October.  Fixing the ordering of the collapsible groups will require changing the contract between STS and MSSQL (to add a non-localized identifier to the groups), which is something I want to do after this release is out the door, because it's a little riskier.
