### ISSUE TITLE
Search Azure subscriptions not working

### ISSUE THREAD

**Issue by amthomas46** [microsoft/vscode-mssql#18240]
Please add "Area" label and repro steps before submitting.

I logged in with Azure (was prompted by the extension to log in) but typing doesnt narrow the subscriptions

![Image](https://github.com/user-attachments/assets/2d99be48-953a-4a11-aa4c-98ce6237d56c)

**Comment by amthomas46** [comment]
i used the other filtering option but nothing shows up for RGs
![Image](https://github.com/user-attachments/assets/e1666f15-ab35-4570-967d-a14d8624c969)

**Comment by Benjin** [comment]
After some investigation, I found that I was getting an error message saying that the resource filter argument I was passing for server-side processing was invalid... for some subscriptions, but not all (or even most).  Curiously, it was consistently the same subscriptions that would return the error, and I didn't notice any pattern to it.  My mind went to permissions, but the query for _all_ resources under that sub is consistently working fine for all subs so that doesn't make sense.
