### ISSUE TITLE
Blank results in query

### ISSUE THREAD

**Issue by ruppeld** [microsoft/vscode-mssql#18338]
- MSSQL Extension Version:v1.25.0
- VSCode Version:v1.9.40
- OS Version:Win 10 Enterprise

Steps to Reproduce:

1.Use MSSQL in VSCode for a few days. Walah! You'll soon notice that your queries have zero results. No it's not bad syntax, the tool is broken.
2. Switch back to SSMS.

**Comment by Benjin** [comment]
Hey @ruppeld, if you're able to supply us with some more information, we can try tracking down what's going wrong so that we can fix it.

Things like specific steps you're following to cause the issue, screenshots or recordings of the bug, or error messages from the VS Code console (`Help` -> `Toggle Developer Tools`) go a long way when it comes to helping us help you.  Thanks!
