### ISSUE TITLE
Execute query & cancel query get broken is connection is dropped

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#228]
Execute query and cancel query don't handle dropped connections very well.  If a connection is dropped (for example the server goes offline) then execute query will run indefinitely  and canceling will also run indefinitely.  We should timeout and fail execute in this scenario and cancel should work as expected.  The error message should tell user the connection isn't available.

**Repro**  
1. Open an SQL file and connect to DB
2. Execute query
3. Take server offline

Expected: Execute query fails in reasonable time with good error message.  Cancel query aborts query execution quickly.

Actual: Execute query runs indefinitely with no error message.  User doesn't know connection has been dropped.

**Comment by julielerman** [comment]
ping ... I just had this happen with 0.3.0. I tried to execute a query before the database was available (docker instance not running). So it hung. I started the db instance then tried to cancel the query but it wasn't connected to the database. I couldn't connect to the database because the query was running (error message). I couldn't cancel the query with the cancel query commend because the database wasn't connected. So I was in a loop.
