### ISSUE TITLE
Insider build connection profile settings are stored in stable user settings file

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#242]
The Insider build's connection profiles settings are stored in the stable build's settings file.  We should read\write connection settings from the correct location based on the build type. 

This is likely due to our custom code to write into settings file.  It would be better to use the new VS Code settings management APIs to avoid this bug.

1. Create connection profile in Insiders build

Expected: Settings stored in insiders user settings file

Actual: Settings stored in stable user settings file

**Comment by MitchellSternke** [comment]
Just a note as to why this is blocked: Even though WorkspaceConfiguration.update() allows you to specify whether you want to write to the user or workspace config file, WorkspaceConfiguration.get() does not tell you which config (user or workspace) the read is performed on.

Until this is resolved, there is a potential for data loss if we simply swap out the existing read/write code for handling settings files with the built-in API's since we can't guarantee that we're writing back to the same file that we read from.

**Comment by kevcunnane** [comment]
It looks like we now have the `inspect` method available via the API that gives us what we need: `{defaultValue: T, globalValue: T, key: string, workspaceValue: T}`. See https://code.visualstudio.com/docs/extensionAPI/vscode-api#WorkspaceConfiguration for more info. We should be able to finally resolve in our next update

**Comment by llali** [comment]
fixed in #991

**Comment by alfonssoo-sql** [comment]
> The Insider build's connection profiles settings are stored in the stable build's settings file. We should read\write connection settings from the correct location based on the build type.
> 
> This is likely due to our custom code to write into settings file. It would be better to use the new VS Code settings management APIs to avoid this bug.
> 
> 1. Create connection profile in Insiders build
> 
> Expected: Settings stored in insiders user settings file
> 
> Actual: Settings stored in stable user settings file
