### ISSUE TITLE
Copy & Paste from output message doesn't work as expected

### ISSUE THREAD

**Issue by fcatae** [Microsoft/vscode-mssql#385]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04 LTS

After running the query, it is not possible to copy the results from the output messages.

Steps to Reproduce:

1. Run any query (eg, select * from sys.dm_exec_query_stats)
2. Go to the Result pane, and try to copy the message (eg, "Total execution time")
3. It will copy the selected cell from Grid Results instead of the text message

**Comment by erickangMSFT** [comment]
Copy feature from Messages pane is not implemented yet but necessary. Added this request as a suggestion.

**Comment by kevcunnane** [comment]
2nd vote for supporting this: https://github.com/Microsoft/vscode-mssql/issues/476

**Comment by benrr101** [comment]
After some initial investigation, I think I know why this is happening. Keyboard shortcut mappings are scoped to the entire window, which means that we can only have one handler for all ctrl+c shortcuts in a results pane. The current mapping checks for a selection in the results grid and if it finds one, copies it. The current implementation automatically selects the first cell of the first grid. This causes the ctrl+c handler to think that there is a selection and copies the cell -- even if there is a selection in the messages pane. There is no way to unselect all cells in the results grids, so the ctrl+c handler will always have some cell(s) to copy.

My suggestion for the solution would be to 1) make it so that there are no cells selected automatically, 2) add a keyboard shortcut to deselect cells (esc?), 3) add a context menu item to "Select None", 4) let the ctrl+c handler pass-through to default behavior if cells aren't selected. @erickangMSFT, your thoughts would be appreciated

In my mind, this would be more of a bug than a suggestion since it's definitely expected that copying text from the screen would work. It's worth noting that SSMS doesn't have this issue. Since messages are in a separate tab, switching to messages tab switches context to the messages tab.

**Comment by kevcunnane** [comment]
@fcatae this fix is checked in - it'll appear in tomorrow's nightly and our next official release. Thanks for raising.
