### ISSUE TITLE
How can I write a task so I can execute sql queries ?

### ISSUE THREAD

**Issue by Charmatzis** [Microsoft/vscode-mssql#416]
- MSSQL Extension Version:  0.1.5
- VSCode Version: 1.7.2
- OS Version: Windows 10

How can I write task so I can execute a sql file?

**Comment by kevcunnane** [comment]
I'd suggest starting with [SQLCMD](https://msdn.microsoft.com/en-us/library/ms180944.aspx) which is available on Windows and also Linux. [This doc](https://msdn.microsoft.com/en-us/library/ms170572.aspx) covers executing a .sql file and you should be able to process the results. 
You do have many other options for example Powershell or [Tedious](https://www.npmjs.com/package/tedious) if you like writing Javascript-based tasks like Gulp.

**Comment by Charmatzis** [comment]
THX for the reply. I was thinking smthing like calling the extention vscode-mssql and the command Execute SQL, pointing the sql file inside the folder and all that as a task in vscode.

**Comment by kevcunnane** [comment]
This isn't supported at present but #424 is a request to do just that. It does require you implement your own extension to VSCode - if you're looking to execute from a task.json task, I'd go back to recommending using one of the command-line options. 

I'm going to close this out for now since I think #424 captures this best. Thanks for raising this.
