### ISSUE TITLE
Reuse connection across multiple queries for same file

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#483]
This is related to #354 - we should be 

Steps to Reproduce:

1. Create a table T1 and write a script with BEGIN TRANSACTION and END TRANSACTION statements
```
-- Create a new table called 'T1' in schema 'dbo'
-- Drop the table if it already exists
IF OBJECT_ID('dbo.T1', 'U') IS NOT NULL
DROP TABLE dbo.T1
GO
-- Create the table in the specified schema
CREATE TABLE dbo.T1
(
    T1Id INT NOT NULL PRIMARY KEY, -- primary key column
    Column1 [NVARCHAR](50) NOT NULL,
    Column2 [NVARCHAR](50) NOT NULL
   -- specify more columns here
);
GO

BEGIN TRANSACTION
INSERT INTO T1 VALUES (1, '1', '2')
ROLLBACK TRANSACTION
```

2. Select the `BEGIN TRANSACTION` command and execute just this
3. Then select the `INSERT INTO` statement and execute
4. Finally execute the `ROLLBACK TRANSACTION` statement

**Expected**:
Get result Command(s) completed successfully as you would in SSMS/SSDT and transaction is committed,
**Actual**:
Because each command is executed in its own connection, this will fail - INSERT will happen outside of a transaction and be committed, and the ROLLBACK command will error with `request has no corresponding BEGIN TRANSACTION`. 

The solution is to reuse a single connection instead of reopening for each query, keep a persistent connection.

**Comment by kevcunnane** [comment]
@coquagli - please work with Ben on this one. It's targeted for Preview 3 rather than current release, so if we have Preview2 targeted bugs we'd prioritize those first.

**Comment by coquagli** [comment]
I currently have the basic functionality for this up and running. However, the changes are either causing a new bug or revealing an existing bug. As of right now, I am unsure whether this is a new bug, so I will document it here.

**Steps to reproduce:**
1. Connect to any database 
2. Run a query like `select * from sys.tables`
3. Keep running the same query 

**Expected:**
Every time the query is run, the results window should be populated with at least _something_

**Actual:** 
Occasionally, the following will appear in the messages window, and the results window will not appear. 
![screen on error - copy](https://cloud.githubusercontent.com/assets/24420239/21402419/2a7faeb2-c76d-11e6-81b7-a10e0c20a57d.PNG)

**Current Investigation Status**
Currently, I am unsure of the exact source of the issue or why it only occurs occasionally, but it has to do with the extension receiving query events in the wrong order. Specifically, in `QueryNotificationHandler.ts`:

- `handleBatchStartNotification` is getting called before `registerRunner`, causing `_queryRunners` to be empty when `handleBatchStartNotification` tries to find the associated `QueryRunner`. 

-  `handleResultSetComplete` is getting called before `handleBatchCompleteNotification`, causing the `_batchSets` in the `QueryRunner` to be empty. 

At first, I though the issue was due to a subtle timing assumption that was revealed when I made the query connection reusable. However, this seems unlikely due to the fact that the issue reproduces almost identically when run against local and remote databases.
