### ISSUE TITLE
Mssql: Failed to load Sql Tools Service

### ISSUE THREAD

**Issue by ravenwish1990** [Microsoft/vscode-mssql#487]
Hi, got this error when I reloaded VSCode after installing MSSQL Extension.
I read around here and found #364 which was about Mint.

Any plans to add support for Arch in a close future?

- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.2
- OS Version: Manjaro 16.10.3 x64 (ArchLinux)

**Comment by kevcunnane** [comment]
Unfortunately not - we're tracking this issue in #417, and as mentioned there this is blocked because .Net Core isn't supported on that platform, and we use it for our service-side code. I'm going to close this issue but we're keeping #417 open to track the request. 

It's worth noting that you can add to the people requesting this on the corefx repository - https://github.com/dotnet/coreclr/issues/4409 is tracking this and more voices may help prioritize the request.
