### ISSUE TITLE
Question: How to output boolean values?

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-mssql#513]
In my quest to find a bug today, I managed to dredge up one difference between SSMS and vscode-mssql: Boolean values. In SSMS, Boolean values are output as a numeric value: 1 for true, 0 for false. In our extension, bool is output as "True" or "False". Although the latter is much easier to interpret but is a departure from the industry standard. What are our thoughts on this?

**Comment by kevcunnane** [comment]
Good question! 

First off I'd check "is the data round trippable using true/false values". A quick inspection shows it is:
- See [Stack Overflow](http://stackoverflow.com/questions/3138029/is-there-a-boolean-data-type-in-microsoft-sql-server-like-there-is-in-mysql) answer.
- Also see our source of truth [MSDN](https://msdn.microsoft.com/en-us/library/ms177603.aspx).

Given that's the case, this really is a preference issue. Defaults:
- True/False is probably easier for the majority of app dev scenarios since it links more closely to how this is modeled in their codebases
- 1/0 is closer to the actual "source of truth" which is the database.

I would go with keeping True/False for now, but we could have this be a user preference if we really cared. Nice find overall.

**Comment by borgdylan** [comment]
I agree with having a setting. Devs such as myself may prefer true/false whereas a DBA may want 1/0.

**Comment by kevcunnane** [comment]
@benrr101 do you want to turn this into a task? I'd put it on the backlog but it'd be an excellent one for advertising as a public contribution?

**Comment by benrr101** [comment]
Sure, sounds good to me.

**Comment by AaronMBertrand** [comment]
I'm all for giving users the option, but please make the *default* setting match SSMS.

**Comment by benrr101** [comment]
Understood, we've discussed quite a bit that we should strive to keep SSMS behavior as our default. I'll make sure that the default setting is to display it as 1/0.

**Comment by benrr101** [comment]
As an update on this, the change to enable configuring the way that BIT columns are displayed is now checked in. The default behavior will be to display them as 1 or 0. This will be rolled out in the next update of the extension within the next week.
