### ISSUE TITLE
Autocomplete for table name only shows partial list

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode-mssql#522]
- MSSQL Extension Version: 1.
- VSCode Version: 0.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Make any query, for example, 

`select * from dbo.`

2. The autocomplete list will only have auto-completion words starting with "d".

![bug1](https://cloud.githubusercontent.com/assets/6411451/21162502/82b51170-c142-11e6-873f-93650b71396e.PNG)

3. Similarly, it for any table, it only gives a list of items starting with the same letter as the first letter of the table. For example, when we execute

`select * from test.`

![bug2](https://cloud.githubusercontent.com/assets/6411451/21162521/a80e883e-c142-11e6-87a8-81b675ac90d7.PNG)

**Comment by kburtram** [comment]
The suggestions in the screenshots above are for the default keyword list.  That list is not context-aware, meaning the same suggestions will be provided regardless of where the cursor is located.  I'm not sure why it's filtering to 'D' and 'T' in the above example, but it doesn't really matter since the keywords won't make sense in that context anyways.

To get schema-based context-aware suggestions you need to connect to a database and wait for the "Updating IntelliSense" message to disappear from the status bar.

**Comment by abist** [comment]
Makes sense. Should I close this issue then, since it's not really an issue?

**Comment by kburtram** [comment]
The filtering to 'D' and 'T' is a little strange, though not really a big problem IMO, since even the full keyword list wouldn't be useful in this case.  There's probably a bug in the default list filtering in this particular syntax.  It's probably a good idea to add a unit test for this syntax and step the code to root cause the bug.

**Comment by abist** [comment]
I did further investigation on this and I figured that this happens because of the async task of message handling. This only happens when you type too fast, so the message handler is still retrieving the autocompletion results. If you type it slowly, it shows no autocompletion list, which is the expected behavior.
