### ISSUE TITLE
Results for the same file appear in different panes when three editor panes are open

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#523]
VS Code state before `select * from sys.databases` is run in the middle pane:
![image](https://cloud.githubusercontent.com/assets/24420239/21165950/532f8df8-c157-11e6-9c6d-277a67c5bf9e.png)

**Actual** VS Code state after `select * from sys.databases` is run in the middle pane:
![image](https://cloud.githubusercontent.com/assets/24420239/21165957/5e4f27ca-c157-11e6-8fa5-7b0e76a93d2b.png)

**Expected** VS Code state after `select * from sys.databases` is run in the middle pane:
![image](https://cloud.githubusercontent.com/assets/24420239/21165962/68cd4b6e-c157-11e6-9c17-8a8c9c5e797a.png)

(Note that here I had the same file open twice, but this is not needed to reproduce the issue)

Steps to Reproduce:
1. Open 3 editor panes
2. Open a SQL file in the left or center pane, then run a query
3. Move the results pane to the right pane
4. Run the query again (or any query in the same SQL file)

**Comment by Raymondd** [comment]
So the only way I have found to detect a column change is to use the onDidChangeTextEditorViewColumn function. Unfortunately this does not seem to work for html preview panes. Because of this I think it may not be possible to know if the pane has changed positions from 2nd to 3rd. I could add a settings to choose either the 1st, 2nd, or 3rd pane. I will contact someone on the VSCode side and see if my findings above are correct.

**Comment by Raymondd** [comment]
After more tinkering I figured out a way to use an existing results window in its corresponding pane. PR incoming.
