### ISSUE TITLE
Temp tables recreates in each query

### ISSUE THREAD

**Issue by penwon** [Microsoft/vscode-mssql#525]
Hello! Is it possible to reuse temp tables in another query?
UPD: This is relates/duplicates to #483

**Comment by kevcunnane** [comment]
Yes, this should be fixed by #483. We are in progress on fixing but it won't make our next release. We expect it to be supported for our 3rd release however, just need to do more testing & validation on the solution. 

Please note that this will allow similar behavior to SSMS / SSDT - each editor has its own connection to the DB, so for multiple queries in that editor window you'll get to use the same temp table. For other files they intentionally have their own connection (so queries can run simultaneously) and so you can't reuse temp tables there.

I'm going to close this as #483 covers this already and we're in progress on that work. Thanks for the suggestion, please keep them coming!
