### ISSUE TITLE
QueryUdtShouldNotRetry failing

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#577]
I missed moving a test in [ExecuteTests.cs](https://github.com/Microsoft/sqltoolsservice/blob/dev/test/Microsoft.SqlTools.ServiceLayer.Test/QueryExecution/ExecuteTests.cs) to the new `Microsoft.SqlTools.ServiceLayer.IntegrationTests` dll. After investigating this test, it looks like there are some issues with it:

After removing the `#if USE_LIVE_CONNECTION`, the test doesn't compile. After fixing the simple compilation error (calling `query.ExecutionTask.Wait();` and passing `null` to `GetFileStreamFactory`) the test still did not pass due to the `Assert.True(query.BatchSummaries[0].HasError);`. I investigated for a bit, but didn't solve the issue. 

As of right now, the test is still ifdef'd out and seems to not be running on Jenkins. The issue seems related to user defined types. should look into preparing a fix, then moving the test to the new dll.

**Comment by pensivebrian** [comment]
You can delete this test, or change the way we validate no retry for queries.

This test was authored when using SqlClient built into .NET Core, which would throw when encountering a CLR UDT. We would retry when encountering this error, which was pointless since this query would never succeed. So, we updated the retry logic to not throw when encountering this exception, and added this test as verification. See [pull/66](https://github.com/Microsoft/sqltoolsservice/pull/66) in the SqlToolsService.

Since then, we started using our own custom version of SqlClient that supports CLR UDTs as binary, so the added test will now passes.

**Comment by coquagli** [comment]
It looks like this test already got removed. Closing this as a result.
