### ISSUE TITLE
[FEAT-REQ] Command execution event history

### ISSUE THREAD

**Issue by eByte23** [microsoft/vscode-mssql#651]
I would think this would be a useful feature.

Have an output tray of 'SQL Execution History' List all commands that have run in order Desc order, most recent first and being able to view the result.

Possibly save result to json on disk? 
For some people this may be an issue if there is sensitive data so maybe a config option to allow this.

But it would be great to be able to see previous query results.

Thanks

**Comment by kevcunnane** [comment]
Thanks for this suggestion. This is definitely something to be considered in the longer term, and discussions internally show there have been requests for something similar in other SQL tools.

As you mentioned, key considerations would be how many queries to keep, how to clean up given the possibility of multiple sessions being open at once. However it's technically feasible to implement this. 

Note that this is also a good candidate for external contributions if anyone wishes to pick this up - the core logic is in the SqlToolsService which would need updating, but that can be discussed since it would mostly be around disposal and state management for multiple queries.
