### ISSUE TITLE
Select all rows of result

### ISSUE THREAD

**Issue by lw-schick** [microsoft/vscode-mssql#659]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 7 Pro SP1

Steps to Reproduce:

1. Send a Query to the SQL Server
2. set the focus to the Results-Table
3. press Ctrl+A

Expected behavior: Select all entries (except line no. and table header)

What the extension actually does: Nothing

**Comment by lw-schick** [comment]
I found out that right-click, select all works. But the short key is not working

**Comment by kevcunnane** [comment]
Thanks for raising this. We will take a look as this isn't the expected behavior - as far as I can tell we should be handling this event but it's not working right now.

**Comment by modliszka** [comment]
What should be expected behaviour in this case for you?
Now it works like selecting all when I'm clicking on the specified column and pressing Ctrl+a:
![image](https://user-images.githubusercontent.com/9070671/43820357-52b81b50-9ae6-11e8-8e75-320cee7d17ab.png)
Are you going to do anything about this topic?

My system:
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.25.1
- OS Version: Windows 10 Pro

**Comment by eashi** [comment]
I believe this should be closed. I have been looking into it and then discovered that there is already part in the documentation where it says this is not possible. [https://github.com/Microsoft/vscode-mssql/wiki/customize-shortcuts#result-view-actions](https://github.com/Microsoft/vscode-mssql/wiki/customize-shortcuts#result-view-actions)
