### ISSUE TITLE
Cannot connect to SQL Server

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-mssql#666]
_From @nivek7 on February 1, 2017 17:26_

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.2.0|

---

I am unable to connect to a SQL Server instance using VSCode and mssql 0.2.0.

I am able to successfully connect to this server using other SQL Dev tools like Razor and Excel. When I try and connect with VSCode, it will eventually timeout.

[11:50:34 AM] Connecting to server "###.###.###.###" on document "untitled:Untitled-1".

[11:54:37 AM] Error connecting to server "###.###.###.###". Details: Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=135; handshake=276; [Login] initialization=0; authentication=0; [Post-Login] complete=14004; 

I have tried the following:
Using an IP Address or hostname (which resolves correctly).
Using different connection parameters (Timeout, Authentication Types etc).

I have no idea what the issue could be. The server is technically remote but is being accessed through a VPN and like I said, I have no issues connecting using Razor or Excel for Mac 2016.

Any thoughts on what this could be?

_Copied from original issue: Microsoft/vscode#19683_

**Comment by kevcunnane** [comment]
What SQL Server version are you connecting to? When investigating a similar issue report (https://github.com/Microsoft/vscode-mssql/issues/638#issuecomment-275648501) I found that there's an issue in .Net Core connecting to SQL Server 2008 R2 instances that haven't been updated to Service Pack 3. If this is a SQL Server 2008 R2 connection, I'd recommend seeing if you can connect to a version with this service pack. If not, please provide the information you can and we will continue to investigate.

**Comment by nivek7** [comment]
The version that I am connecting to is:
Microsoft SQL Server 2008 R2 (SP1) - 10.50.2500.0 (X64) 
	Jun 17 2011 00:54:03 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

**Comment by kevcunnane** [comment]
OK - that matches the other reported issue. The problem is that .Net Core does not support connecting to SP1, and the recommended solution is upgrading the server to SP3. The reference issue in the CoreFx repository is https://github.com/dotnet/corefx/issues/9719. I'll leave this issue open to track the bug, but unfortunately we're blocked unless SqlClient in CoreFx is changed to support this.

**Comment by nivek7** [comment]
Our database is hosted. Coincidentally, it is being update this weekend to SQL 2014, so my issue should be remedied by Monday. Thank you for you help.

**Comment by kevcunnane** [comment]
@nivek7 glad it'll be resolved. I followed up with the Connectivity team and there is a good reason for this limitation - see https://github.com/dotnet/corefx/issues/5187. Basically any fix to support this would open up a vulnerability, so they will always require SQL Server instances to be on SP3. As such, I am going to close out the issue since it's by design.

**Comment by ddotlic** [comment]
Just a note for the others stumbling upon this problem: if you have SQL 2008 **non-R2** you need to update to _SP4_ (10.0.6000.29).

**Comment by flavioeb-ciandt** [comment]
I suppose there is the same problem with SQL Server 2005.

I'm having the same error with it.

Is there any fix or intention to fix it in VS Code? Upgrade the database is not an option form me right now.

Thanks.

**Comment by digggggggggg** [comment]
I've just been through this problem and nothing I found anywhere helped, so I thought I'd share the solution that helped me.

Turns out my client had used "username@domain.com" as their login instead of just "username". Looks like there is some functionality internal to excel that tries to authenticate the user via that domain, and thus, the connection times out without a response. Don't create logins with "@domain.com" in SQL Server.

Hope this helps someone in future.
