### ISSUE TITLE
bit output is rendered as boolean

### ISSUE THREAD

**Issue by AaronMBertrand** [Microsoft/vscode-mssql#690]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.0
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. `SELECT CONVERT(bit,1);`

Actual results:

    True

Expected results:

    1

**Comment by PierreRossouw** [comment]
Yes agreed - I actually would prefer the way SSMS does this - returning 1 for True and 0 for False in all boolean/bit grid results. It's very difficult to visually scan a column filled with TRUE TRUE TRUE FALSE TRUE TRUE looking for the odd ones out. Perhaps a config setting?

**Comment by benrr101** [comment]
Thanks for your feedback on this issue! I raised this question a while back (https://github.com/Microsoft/vscode-mssql/issues/513) and got the same sort of response from our PM @erickangMSFT. Since there's a decent amount of support for a config setting (and I know where to put the code), I'll get started on implementing it.

**Comment by benrr101** [comment]
As an update on this, the change to enable configuring the way that BIT columns are displayed is now checked in. The default behavior will be to display them as 1 or 0. This will be rolled out in the next update of the extension within the next week.

I'll close this issue, but feel free to respond back or open another issue if there's still problems.
