### ISSUE TITLE
Need better presentation mode

### ISSUE THREAD

**Issue by AaronMBertrand** [Microsoft/vscode-mssql#727]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.4

Yesterday I gave a presentation at SQL Saturday Boston and I decided, for the first time, to use VS Code against SQL Server on Linux, to achieve a more seamless transition between slide deck, demos, and back.

This worked great on my local machine until I hooked up to the projector and had to increase my fonts for the people in the back of the room. This made the interface a disaster, and made it very frustrating to show the results of the demos. It didn't matter if the results/messages were to the side or below, but several issues made for a very sad experience:

![vscode-zen](https://cloud.githubusercontent.com/assets/22244117/23340686/93abf808-fc08-11e6-92ce-453f04812efe.png)

It turned out this was a terrible choice, and I would have been much better off using SSMS inside a Windows VM.

But I still have hope that the interface will be more flexible and that it can be customized to present well. Those panels and grid results really need to expand to fill the space they're in and be easily adjustable. In order to show results in a grid, I often had to shrink the code window to almost nothing, and to show messages I had to scroll and scroll and scroll.

**Comment by kevcunnane** [comment]
@AaronMBertrand thanks Aaron, we hear you loud and clear on this issue. Unfortunately, there is a known issue with WebViews in VSCode, and that's how extensions like ours plug in UI. This means that when you change the zoom level, as described in #280, the WebView gets shrunk by the zoom instead of filling the new space with larger font size etc. You can see by the volume of issues linked to the main VSCode tracker (https://github.com/Microsoft/vscode/issues/5745) that many others feel the pain of this too. 

Long term, we can only work around this if it's fixed and updated in VSCode, or a full 1st party UI extension support is added. It's not clear if/when that will happen, so until then please follow the workaround below which should at least unblock you for future presentations. Again, I wish we had a better story for this but right now this is the best practice solution we have available.

**Workaround**
To workaround this, the best way is to up the font for the editor and the MSSQL Results view to something like 18:
![image](https://cloud.githubusercontent.com/assets/10819925/23376096/bfb1214e-fcdf-11e6-9ec1-8a7e195efef4.png)

This ends up looking as it does below - significantly better than trying to use the zoom control. Note that I've created a bug #728 to track issues scaling to 20px or larger, and we'll definitely work to get this done for our next release (not the current 0.3.0, which is locked down).

![image](https://cloud.githubusercontent.com/assets/10819925/23376078/b1d20480-fcdf-11e6-8211-36704ded7b0c.png)

**Comment by kevcunnane** [comment]
@AaronMBertrand - can you update to VSCode 1.13 and try again? It should now "just work" as VSCode has shipped an updated electron version with the fix.

**Comment by kevcunnane** [comment]
@AaronMBertrand - I'm going to close this as zoom now works as expected thanks to the VSCode / Electron fix
