### ISSUE TITLE
Error connecting to SQL DW database

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#731]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Connect to SQL DW database

Expected: connection successful

Actual: [12:54:12 PM] Error connecting to server "...". Details: Parse error at line: 1, column: 5: Incorrect syntax near 'ANSI_NULLS'.

**Comment by kburtram** [comment]
The connection worked after removing recent connections and deleting my connection profiles from the settings file.  I most have had invalid metadata cached for our test server.

**Comment by kevcunnane** [comment]
This is a bug in the connection cache - it's at the server level which is incorrect. Azure SQL DB and Azure SQL DW database instances both exist on regular Azure servers, and master always reports as a SQL DB. Therefore we need to use DB-level property caching instead of server-level. I'll update to do this.

**Comment by kburtram** [comment]
Closing stale internally created issues.
