### ISSUE TITLE
[Feature] Save As Excel

### ISSUE THREAD

**Issue by wjzhou** [Microsoft/vscode-mssql#739]
As title, Save as Excel feature similar to Save as Json/Save as Excel.

Scenario: In my place, I need to send Ad-hoc query result to other staffs in excel format. 

This feature is missing in ssms, implementing it will give us a unique feature to sell.

**Comment by benrr101** [comment]
Thanks for your feedback! Right now, saving to CSV is the best we can offer, but as you note CSV can be opened with Excel. If we can make the scenario of saving to CSV and opening in Excel better for you, we'd love to address that. If you could provide us with some more details on what scenarios don't work for you (such as cells with certain characters, etc), this would help us find concrete ways to improve the CSV feature.

You mentioned UTF8 characters being an issue. We use UTF8 to encode the file, but have considered UTF16 (with BOM) as well, since this would enable full support of N* columns. Additionally, you mentioned line breaks in the data. Do you mean that line breaks appear in the data when they should not? Or that line breaks are omitted from the data when they should be included? We make an effort to wrap multi-line cells in quote marks to preserve the data, but it's possible that this isn't functioning correctly when the CSV is opened in another program. If so, we should address this issue.

Additionally, I'm not ruling out a save to Excel feature. Excel files are much more complicated than simple CSV files. And as such, coding up this kind of feature would take a fair bit of time. It wouldn't be impossible, especially if we can find a library to help with writing Excel files. But, we might not be able to tackle this task for a while.

**Comment by wjzhou** [comment]
Thank you for the thoughtful response. I have retested the situation and find the UTF8 with BOM is all I need for the encoding part. (both Excel 2010/2016 with latest updates). And Excel handles the line break correctly too.
 
Thus, I think an option to save csv with UTF8-BOM should be sufficient in my scenario. (I have updated my description)


For the Excel library, there is no working library (I'm aware of) for dotnet core yet. But xlsx based Excel file is not that complicated to create by hand, it is just a zip file with 6 files. 

Since the csv will work, the save as excel feature is not that urgent to have. I wrote a prototype library last night, it is one file with 400 lines of code. If you want, I can send a pull request to the sqltoolsservice repository. If you don't want to maintain it, that's fine too.

**Comment by benrr101** [comment]
Thanks for the response! I did a little bit more research and it looks like CSV on Excel isn't very friendly... http://stackoverflow.com/questions/6588068/which-encoding-opens-csv-files-correctly-with-excel-on-both-mac-and-windows shows that UTF8 is probably the worst option since it is scrambled on both windows and mac. UTF8 w/BOM works perfectly on Windows but is still scrambled on mac. I just now tested UTF-16LE w/o BOM and it worked on Excel 2016 on windows and mac. This would probably be the best option at this point since it will permit all of the Unicode characters that SQL Server supports. This would be a simple 1-line change in our code, which is nice 😃 

As for the Excel export, ***we would be overjoyed to have you contribute to add this feature!*** I snuck a peek at your feature/SaveAsExcel branch and I'm quite impressed by what you cranked out in such a short period -- especially that you picked up on the SaveAsFileWriter architecture. If you'd like to submit this as a pull request, there's a couple contributor license hoops you need to get through but I can help you with that if necessary. 

One note I'd like to add to your code before we get to reviewing it: If possible, could we utilize the System.Xml library to write or build the document with nodes rather than write strings directly to file? Totally understandable that since this is prototype code that this isn't the final revision, but I figured a change like that should be noted up-front so you're not surprised during the review.

Thanks again!

**Comment by benrr101** [comment]
@wjzhou, any updates on this? We're all quite excited to bring in your branch for exporting to Excel! If you need any assistance with using an XMLWriter to generate the files, let me know 😃

**Comment by wjzhou** [comment]
Sorry for the late.

It took longer than I thought. If there were anything wrong, Excel and google sheets doesn't give any detailed information about the error.

I have created a [pull request](https://github.com/Microsoft/sqltoolsservice/pull/279) against the  https://github.com/Microsoft/sqltoolsservice repository.

Please take a look. I'll add more tests after the first round review.

**Comment by wjzhou** [comment]
I create a test project to demo the helper class. https://github.com/wjzhou/excel-library-test

https://github.com/wjzhou/excel-library-test/blob/master/src/testexcel/Program.cs#L18-L33

**Comment by rmunn** [comment]
There appears to be good news! Excel may soon be able to write (and, one would assume, also read) UTF-8 files. See https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/10006149-support-saving-csv-in-utf-8-encoding for more details.

**Comment by benrr101** [comment]
This feature is now checked into our dev branch and will be released in the next release. Will close this issue for now.
