### ISSUE TITLE
Unable to save connection profile on Win7 x64

### ISSUE THREAD

**Issue by afittro** [Microsoft/vscode-mssql#765]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10.1
- OS Version: Windows 7 pro x64, SP1

I installed the newly released 0.3.0 on both a laptop and a desktop. No installation problems now, thanks to issue 711's fix.

However, when I enter F1->sqlman and try to create a profile, the process works fine until I give it a name and Save. At that point I get `mssql: Error: Unable to load connection profiles from [C:\Users\afittro\AppData\Roaming\Code\User\settings.json]. Check if the file is formatted correctly.`

I get that same error if I later open an SQL file and do F1->sqlcon or any other mssql command. Well, the error is different for MSSQL: Use Database. That one tells me no connection was found. Please connect first.

That file seems to have saved perfectly though.
```
{
    "mssql.logDebugInfo": true,
    "mssql.maxRecentConnections": 5,
    "mssql.connections": [
        {
            "server": "{{dbprod}}",
            "database": "{{tblName}}",
            "user": "{{me}}",
            "password": "{{secret}}"
        }
    ],
    "mssql.format.keywordCasing": "lowercase",
    "editor.tabSize": 2,
    "extensions.autoUpdate": true,
    "http.proxyStrictSSL": false,
}
```

@kevcunnane asked for me to send the file in email, but this is the whole of the file in question. It is already obfuscated. PS when I went thru the sqlman command's wizard and it asked me to name this profile at the end, I entered "dbprod" (without quotes) so I could find this profile later. I see no mention of a profile name in the settings file. Did it maybe get confused in that I used dbprod as both name of profile entry and name of database? (dbprod is just an entry in my hosts file for an internal server's IP)

**Comment by kevcunnane** [comment]
@afittro OK, so I got to the bottom of this. We must be parsing in "strict" mode, or our parser doesn't like incorrectly formatted settings files. The `,` after "http.proxyStrictSSL" is breaking us. You'll actually see a red error at the end of the file stating `property expected`. Removing that will let you add a connection.
One more note: the `"{{dbprod}}"` format is just for the sample we use. If you actually manage to create a connection you'll see that for real ones, we don't have any `{{` or `}}` instances.

I'll leave this issue open since we should be more tolerant to JSON formatting errors when parsing. But this should be enough to unblock you and let you use our extension (finally!)

**Comment by afittro** [comment]
Exactly right and thank you for being you :) All problems solved. A recent query just executed without issues.

ps., I'm 52 and have used code editors for 27 years and this is the best I've seen. Keep it up.
