### ISSUE TITLE
Can't create SQL Profile

### ISSUE THREAD

**Issue by sl-fedegiust** [Microsoft/vscode-mssql#807]
- MSSQL Extension Version: 0.30.0
- VSCode Version: 1.11.1
- OS Version: OS X 10.12.3

Steps to Reproduce:

1. Installed VS Code
2. Installed MS SQL Extensions following instructions here https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-develop-use-vscode
3. Created a new file
4. Set the file to SQL
![image](https://cloud.githubusercontent.com/assets/13888424/24797526/02bee628-1b68-11e7-8a39-43f4d18c7206.png)

5. Opened command palette to create a new connection profile
6. Enter connection details and always get this error

![image](https://cloud.githubusercontent.com/assets/13888424/24797504/ec3c269a-1b67-11e7-9138-0ef64ab63ecf.png)

```
mssql: Error: Unable to load connection profiles from [/Users/federicogiust/Library/Application Support/Code/User/settings.json]. Check if the file is formatted correctly.
```

This is the content of my settings.json
```
// Place your settings in this file to overwrite the default settings
{
    "files.associations": {
        "*.asp": "asp"
    },
    "workbench.colorTheme": "Visual Studio Dark",
}
```

**Comment by sl-fedegiust** [comment]
**UPDATE**

After I removed the extra comma on this line

```
"workbench.colorTheme": "Visual Studio Dark",
```
on my settings.json I was able to save the profile and connect successfully.

**Comment by kburtram** [comment]
@sl-fedegiust thanks for reporting this issue.  We check if the code to save profiles can be a little more robust to better handle JSON deserialization errors.

**Comment by kevcunnane** [comment]
@MattIrv @huypha @kburtram - I took a look at how VSCode does this. They have pretty robust JSON parsing and validation code at [JSON.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/json.ts), which is used by the  [ConfigModel<T>.update method](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/configuration/common/model.ts) to get the settings. We could leverage this logic, but would need a bit of rewriting since they are handling merging of settings etc. It's do-able but might be hard to get in for this release.

An alternative would be to re-analyze whether using built in APIs would give us a merged connections list (from user and workspace settings). This wasn't supported in earlier releases but they've done work in this area. If it worked, we'd get the "correct" behavior from the get-go, including using the correct settings file in Insiders builds, and handling the thorny issue of users adding connections to both workspace and user settings.

**Comment by kburtram** [comment]
@kevcunnane moving to the VS Code API directly would be the preferred fix.  It sounds like a medium-sized change.  Do you want to hold the GA release for this issue, or take the fix in GA+1?

**Comment by MattIrv** [comment]
I took a quick look at this since the code is in the same place I'm working with for #786 , but it doesn't look like the VSCode API supports merging user and workspace settings.

For now, VSCode's documentation says that workspace configurations override user configurations if set (see https://code.visualstudio.com/docs/getstarted/settings), which matches the API's behavior.

**Comment by kburtram** [comment]
@MattIrv thanks for looking in this.  I'm recalling now discussing the merging workspace\user settings issue you've mentioned.  I vaguely remember there was a case where we could lose user settings, though don't recall the specific details.

It sounds like we need to do a bit more investigation to resolve this correctly.  I'll remove it from the next release milestone for now since I don't think we'll have time to implement and test this before that release early next week.

**Comment by kevcunnane** [comment]
Another note - checking the VSCode doc page pointed me to https://www.npmjs.com/package/jsonc-parser for json parsing. I think this could be used to get the robust parsing we need
