### ISSUE TITLE
[Suggestion] Double clicking column header auto-sizes to result contents, not header text.

### ISSUE THREAD

**Issue by lampij** [Microsoft/vscode-mssql#906]
- MSSQL Extension Version: 1.0
- VSCode Version: 1.13.1
- OS Version: Win 7 Pro SP1

Steps to Reproduce:

1. Return result set where content length is greater then column header length
2. While cursor is in 'draggable' mode over left-hand side of header, double click.

**Comment by kevcunnane** [comment]
@lampij thanks for the suggestion. We've taken a look at this a couple of times and it turns out to be harder than expected using the SlickGrid implementation we currently have. The core tracking issue is https://github.com/Microsoft/vscode-mssql/issues/798 - it's currently backlogged but I'm going to close this and leave that as the active item since it has context on possible approaches etc. You can monitor that to see if we make any progress on it, but as mentioned we're currently lacking a clean solution.

**Comment by lampij** [comment]
@kevcunnane Thank you for the response! Great work with this extension, and best of luck.
