### ISSUE TITLE
Problem to connect on Amazon RDS

### ISSUE THREAD

**Issue by FellipeMedeirosSilva** [microsoft/vscode-mssql#908]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.13.1
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. Configure the connection to RDS Server
2. After a long time i receive a timeout message (I connect normally on sql management studio using same access url and login/password)

**Comment by kevcunnane** [comment]
Apologies for the delayed response. I wonder if this is a firewall or other issue, given you're on Mac instead of Windows? Could you try connecting using [SQLCMD](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connecting-with-sqlcmd)? I can try to investigate this at some point but, unsurprisingly, don't have an Amazon RDS account so if you could verify it's a general issue with our tool and not machine-specific this would be a huge help.

**Comment by FellipeMedeirosSilva** [comment]
Good Night Kevin, how are you?

I try on two different networks and the problem still remain. I Try on windows using parallels on this mac and works normally. If i give to you a user on Amazon RDS helps?

Best regards,
Fellipe M.

**Comment by abist** [comment]
@FellipeMedeirosSilva Could you try connecting with the latest version of the extension? Feel free to reopen the issue if you still experience the same problem.
