### ISSUE TITLE
Suggestion: Drag'n'drop cell value from 'Result' grid to code editor will result in code snippet 'and [column name] = [cell value]'

### ISSUE THREAD

**Issue by 4mitch** [microsoft/vscode-mssql#922]
- MSSQL Extension Version:1.0.0
- VSCode Version:1.14.0
- OS Version:Win10

Steps to Reproduce:

1.Drag'n'drop cell value from 'Result' grid to code editor
2.Will result in code snippet '_and [column name] = [cell value]_'

**Comment by kevcunnane** [comment]
This is a nice suggestion, but might be difficult to pull off since we run inside a separate process to the main VSCode UI. It's certainly possible someone could look into this (e.g. ensuring drag does a copy to the clipboard and seeing if this is accepted by the code editor window), but might be a nice use case for a public contribution.

**Comment by kburtram** [comment]
Unfortunately, the VS Code extensibility model doesn't support drag-n-drop between a webview UI (like the result grid) and the code editor window.  Closing this older issue as "Won't Fix".
