### ISSUE TITLE
Creating connection profile through command palette will format and remove all comments from user setttings in settings.json

### ISSUE THREAD

**Issue by madlovin** [Microsoft/vscode-mssql#959]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.1
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

1. In Visual Studio Code, type `CTRL + ,` to open the settings.json file
2. On the right pane within the curly braces on a new line (e.g., the user settings), type `//This is a test`
3. Type `CTRL + S` to save the settings.json file
4. Follow the steps "Connect to SQL Server" as described in [tutorial](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-develop-use-vscode) to create a new **valid** connection
5. In Visual Studio Code, type `CTRL + ,` to open the settings.json file
6. Observe that the comment line has been removed

**Comment by kevcunnane** [comment]
@madlovin do you know if this just started occurring in 1.1? I think this is likely due to the fact we read in all the JSON and use a serializer to print it out again. That's where we're losing comments. We have some work tagged for the next release to start using the VSCode APIs for reading/writing settings again, which should help with this overall. We can take a look at this when doing that.

**Comment by madlovin** [comment]
@kevcunnane I just installed the extension yesterday, so I have no prior experience to share.

**Comment by kevcunnane** [comment]
Thanks for confirming. I believe this is a long-standing issue in that case. We'll look at it for our next update, hopefully we can fit it in.

**Comment by llali** [comment]
fixed in #991
